apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  labels:
    app: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      containers:
      - image: docker.io/bootdotdev/synergychat-crawler:latest
        name: synergychat-crawler
        env:
          - name: CRAWLER_PORT
            valueFrom:
              configMapKeyRef:
                name: synergychat-crawler-configmap
                key: CRAWLER_PORT
          - name: CRAWLER_KEYWORDS
            valueFrom:
              configMapKeyRef:
                name: synergychat-crawler-configmap
                key: CRAWLER_KEYWORDS
